# Generated by Django 2.2.3 on 2019-07-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favoriteapi', '0003_auto_20190711_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user_id',
            new_name='user',
        ),
    ]
