# Generated by Django 2.2.3 on 2019-07-12 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favoriteapi', '0005_auto_20190711_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='favorite', to='favoriteapi.Category'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='ranking',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
