# Generated by Django 2.2.3 on 2019-07-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favoriteapi', '0007_auto_20190717_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfavorite',
            name='modified_at',
        ),
    ]
