# Generated by Django 2.2.3 on 2019-07-19 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favoriteapi', '0009_remove_historicalfavorite_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalfavorite',
            name='user',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='description',
            field=models.TextField(blank=True, max_length=300, validators=[django.core.validators.MinLengthValidator(10, message='Please provide a description with more than ten characters')]),
        ),
        migrations.AlterField(
            model_name='historicalfavorite',
            name='description',
            field=models.TextField(blank=True, max_length=300, validators=[django.core.validators.MinLengthValidator(10, message='Please provide a description with more than ten characters')]),
        ),
    ]
