# Generated by Django 2.2.4 on 2019-08-09 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favoriteapi', '0010_auto_20190719_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category']},
        ),
    ]
